// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class datecounter555 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datecounter555));
        
        string IMigrationMetadata.Id
        {
            get { return "201408072118144_date-counter555"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
