// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class countersIsOff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(countersIsOff));
        
        string IMigrationMetadata.Id
        {
            get { return "201408070943037_countersIsOff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
