// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class differentStates1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(differentStates1));
        
        string IMigrationMetadata.Id
        {
            get { return "201407171039536_differentStates1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
