// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class datetime2todatetime2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datetime2todatetime2));
        
        string IMigrationMetadata.Id
        {
            get { return "201411232312372_datetime2todatetime2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
