// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dbgennone : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbgennone));
        
        string IMigrationMetadata.Id
        {
            get { return "201408151007233_dbgen-none"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
