// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class initialvaluefornewcounter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(initialvaluefornewcounter));
        
        string IMigrationMetadata.Id
        {
            get { return "201408140927321_initial-value-for-new-counter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
