// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class dbgenidentity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dbgenidentity));
        
        string IMigrationMetadata.Id
        {
            get { return "201408151008447_dbgen-identity"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
