// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class notnulladdresshouse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notnulladdresshouse));
        
        string IMigrationMetadata.Id
        {
            get { return "201407251138258_not-null-address-house"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
