// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class servicecounterrel1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(servicecounterrel1));
        
        string IMigrationMetadata.Id
        {
            get { return "201408071302340_service-counter-rel1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
