// <auto-generated />
namespace DalaWeb.Domain.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class isOffForStamp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(isOffForStamp));
        
        string IMigrationMetadata.Id
        {
            get { return "201408121303351_isOffForStamp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
